services:
  postgres:
    image: postgres:18
    container_name: calmi-postgres
    environment:
      POSTGRES_USER: calmi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calmi_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U calmi"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
